# Generated by Django 5.0.14 on 2025-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="Pending", editable=False, max_length=20),
        ),
    ]
