# Generated by Django 5.0.14 on 2025-07-22 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0002_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=20, unique=True
            ),
        ),
    ]
